route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h
  receiver: '<NameOfTarget>'

receivers:
- name: "<NameOfTarget>"
  webhook_configs:
  - url: 'http://target.url'
