version: "3.9"

volumes:
  prometheus_data:

services:

    prometheus:
        container_name: prometheus
        ports:
            - 9090:9090
        volumes:
            - ./prometheus.yml:/etc/prometheus/prometheus.yml
            - ./rules.yml:/etc/prometheus/rules.yml
        command:
            - --config.file=/etc/prometheus/prometheus.yml
        image: prom/prometheus

    alertmanager:
        container_name: alertmanager
        ports:
            - 9093:9093
        volumes:
            - ./alertmanager.yml:/etc/alertmanager/alertmanager.yml
        command:
            - '--config.file=/etc/alertmanager/alertmanager.yml'
        image: prom/alertmanager

    cadvisor:
        container_name: cadvisor
        ports:
            - 8590:8080
        volumes:
            - /:/rootfs:ro
            - /var/run:/var/run:rw
            - /sys:/sys:ro
            - /var/lib/docker/:/var/lib/docker:ro
        image: gcr.io/cadvisor/cadvisor
    