global:
  scrape_interval:     15s
  evaluation_interval: 15s
  external_labels:
      monitor: 'infra-01'

rule_files:
  - 'alert.yml'

alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets:
      - "192.168.1.116:9093" # Modify IP 

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets:
        - localhost:9090

  - job_name: 'node'
    static_configs:
         - targets:
           - 192.168.1.116:9100 # Modify IP 
  